"""Developmentally explicit branching architecture generated by persistent tips."""

from __future__ import annotations

import math
from dataclasses import dataclass
from enum import StrEnum

import numpy as np
from scipy.spatial import ConvexHull, QhullError

from rootfpt.multiscale.agent import TipTraits, _soil_response
from rootfpt.multiscale.soil import SoilState


class SiteStatus(StrEnum):
    POTENTIAL = "potential"
    DORMANT = "dormant"
    ABORTED = "aborted"
    EMERGED = "emerged"


@dataclass(frozen=True)
class RootType:
    name: str
    tip_traits: TipTraits
    radius: float
    branch_spacing_mean: float
    branch_spacing_shape: float
    developmental_delay_mean: float
    branch_angle_mean: float
    branch_angle_sd: float
    mortality_rate: float = 0.0
    dormancy_rate: float = 0.0
    successor: str | None = None


@dataclass(frozen=True)
class EmergenceResponse:
    intercept: float = 2.0
    water: float = 1.0
    nutrient: float = 0.5
    impedance: float = -1.0
    carbon: float = 0.5
    dry_memory: float = -0.5
    abortion_probability: float = 0.05
    dormancy_probability: float = 0.05


@dataclass
class PotentialSite:
    site_id: int
    parent_tip_id: int
    parent_node: int
    position: np.ndarray
    parent_orientation: float
    parent_order: int
    root_type: str
    initiation_time: float
    emergence_time: float
    side: float
    status: SiteStatus = SiteStatus.POTENTIAL


@dataclass(frozen=True)
class ArchitectureSegment:
    segment_id: int
    start_node: int
    end_node: int
    parent_segment_id: int | None
    tip_id: int
    root_type: str
    order: int
    start: tuple[float, float]
    end: tuple[float, float]
    radius: float
    created_time: float

    @property
    def length(self) -> float:
        return math.dist(self.start, self.end)

    @property
    def orientation(self) -> float:
        return math.atan2(self.end[1] - self.start[1], self.end[0] - self.start[0])


@dataclass
class _GrowingTip:
    tip_id: int
    node: int
    parent_segment_id: int | None
    root_type: str
    order: int
    position: np.ndarray
    angle: float
    age: float
    arc_length: float
    next_site_arc: float
    dry_memory: float
    birth_time: float
    mortality_time: float
    dormancy_time: float
    spacing_index: int
    active: bool = True


@dataclass(frozen=True)
class Architecture:
    nodes: np.ndarray
    segments: tuple[ArchitectureSegment, ...]
    sites: tuple[PotentialSite, ...]
    tip_paths: dict[int, tuple[int, ...]]
    duration: float

    def metrics(self) -> dict[str, float]:
        if not self.segments:
            return {
                "total_length": 0.0,
                "depth": 0.0,
                "lateral_width": 0.0,
                "convex_hull_area": 0.0,
                "tortuosity": 1.0,
                "branch_count": 0.0,
                "orientation_entropy": 0.0,
            }
        lengths = np.asarray([segment.length for segment in self.segments])
        angles = np.asarray([segment.orientation for segment in self.segments])
        histogram, _ = np.histogram(angles, bins=12, range=(-np.pi, np.pi), weights=lengths)
        probabilities = histogram / max(float(np.sum(histogram)), 1e-15)
        nonzero = probabilities > 0
        entropy = -float(np.sum(probabilities[nonzero] * np.log(probabilities[nonzero])))
        path_tortuosities = []
        for path in self.tip_paths.values():
            if len(path) < 2:
                continue
            points = self.nodes[np.asarray(path)]
            path_length = float(np.sum(np.linalg.norm(np.diff(points, axis=0), axis=1)))
            displacement = float(np.linalg.norm(points[-1] - points[0]))
            if displacement > 1e-12:
                path_tortuosities.append(path_length / displacement)
        try:
            hull_area = float(ConvexHull(self.nodes).volume) if len(self.nodes) >= 3 else 0.0
        except QhullError:
            hull_area = 0.0
        return {
            "total_length": float(np.sum(lengths)),
            "depth": float(np.max(self.nodes[:, 1]) - np.min(self.nodes[:, 1])),
            "lateral_width": float(np.max(self.nodes[:, 0]) - np.min(self.nodes[:, 0])),
            "convex_hull_area": hull_area,
            "tortuosity": float(np.mean(path_tortuosities)) if path_tortuosities else 1.0,
            "branch_count": float(sum(site.status == SiteStatus.EMERGED for site in self.sites)),
            "orientation_entropy": entropy,
            "order_0_length": float(
                sum(segment.length for segment in self.segments if segment.order == 0)
            ),
            "order_1_length": float(
                sum(segment.length for segment in self.segments if segment.order == 1)
            ),
            "order_2_length": float(
                sum(segment.length for segment in self.segments if segment.order >= 2)
            ),
        }

    def root_length_density_by_depth(self, bins: np.ndarray) -> np.ndarray:
        midpoints = np.asarray(
            [(segment.start[1] + segment.end[1]) / 2.0 for segment in self.segments]
        )
        lengths = np.asarray([segment.length for segment in self.segments])
        density, _ = np.histogram(midpoints, bins=bins, weights=lengths)
        return density / np.diff(bins)


def _sample_spacing(root_type: RootType, rng: np.random.Generator) -> float:
    return float(
        rng.gamma(
            root_type.branch_spacing_shape,
            root_type.branch_spacing_mean / root_type.branch_spacing_shape,
        )
    )


def _logistic(value: float) -> float:
    return 1.0 / (1.0 + math.exp(-float(np.clip(value, -40.0, 40.0))))


DRY_MEMORY_RELAXATION_TIME_DAYS = -0.08 / math.log(0.95)


def _dry_memory_decay(elapsed_time: float) -> float:
    """Continuous-time form of the legacy 0.95 factor at 0.08 day."""
    return math.exp(-elapsed_time / DRY_MEMORY_RELAXATION_TIME_DAYS)


class _KeyedRandom:
    """Order-independent random variates for biological events."""

    def __init__(self, master_seed: int):
        self.master_seed = int(master_seed)

    def generator(self, stream: int, *keys: int) -> np.random.Generator:
        return np.random.default_rng(
            np.random.SeedSequence([self.master_seed, int(stream), *map(int, keys)])
        )

    def uniform(self, stream: int, *keys: int) -> float:
        return float(self.generator(stream, *keys).random())

    def normal(self, stream: int, *keys: int) -> float:
        return float(self.generator(stream, *keys).normal())

    def gamma(self, shape: float, scale: float, stream: int, *keys: int) -> float:
        return float(self.generator(stream, *keys).gamma(shape, scale))

    def exponential(self, rate: float, stream: int, *keys: int) -> float:
        if rate <= 0.0:
            return math.inf
        return float(self.generator(stream, *keys).exponential(1.0 / rate))


class _CoupledBrownianPath:
    """Counter-based Brownian path shared by nested integration grids.

    Values at the fixed quantum boundaries are exact Brownian increments.
    Piecewise-linear interpolation handles off-grid biological event times, so
    coarse and fine integrations query exactly the same resolved path.
    """

    def __init__(
        self,
        random: _KeyedRandom,
        duration: float,
        quantum: float,
    ):
        if quantum <= 0.0:
            raise ValueError("brownian_quantum must be positive")
        self.random = random
        self.duration = duration
        self.quantum = quantum
        self.count = int(math.ceil(duration / quantum))
        self.paths: dict[int, np.ndarray] = {}

    def _path(self, tip_id: int) -> np.ndarray:
        if tip_id not in self.paths:
            generator = self.random.generator(100, tip_id)
            increments = math.sqrt(self.quantum) * generator.normal(size=self.count)
            self.paths[tip_id] = np.concatenate(([0.0], np.cumsum(increments)))
        return self.paths[tip_id]

    def value(self, tip_id: int, time: float) -> float:
        clipped = float(np.clip(time, 0.0, self.duration))
        scaled = clipped / self.quantum
        index = min(int(math.floor(scaled + 1e-12)), self.count)
        fraction = scaled - index
        path = self._path(tip_id)
        if fraction <= 1e-10 or index == self.count:
            return float(path[index])
        fraction = min(max(fraction, 0.0), 1.0)
        return float(path[index] + fraction * (path[index + 1] - path[index]))

    def increment(self, tip_id: int, start: float, end: float) -> float:
        return self.value(tip_id, end) - self.value(tip_id, start)


def _clip_to_domain(
    start: np.ndarray,
    end: np.ndarray,
    soil: SoilState,
) -> tuple[np.ndarray, float, bool]:
    """Clip a proposed segment at its first rectangular-domain contact."""
    x0, x1 = soil.grid.x_limits
    z0, z1 = soil.grid.z_limits
    displacement = end - start
    fraction = 1.0
    for coordinate, delta, lower, upper in (
        (start[0], displacement[0], x0, x1),
        (start[1], displacement[1], z0, z1),
    ):
        if delta > 0.0 and coordinate + delta > upper:
            fraction = min(fraction, (upper - coordinate) / delta)
        elif delta < 0.0 and coordinate + delta < lower:
            fraction = min(fraction, (lower - coordinate) / delta)
    clipped = fraction < 1.0 - 1e-12
    return start + max(fraction, 0.0) * displacement, max(fraction, 0.0), clipped


def simulate_architecture(
    *,
    soil: SoilState,
    root_types: dict[str, RootType],
    primary_type: str,
    response: EmergenceResponse,
    duration: float,
    dt: float,
    rng: np.random.Generator,
    initial_position: tuple[float, float] = (0.0, 0.0),
    initial_orientation: float = np.pi / 2.0,
    max_order: int = 2,
    max_tips: int = 500,
    carbon_factor: float = 1.0,
    brownian_quantum: float = 0.02,
) -> Architecture:
    """Grow a branching network whose parent axes continue after emergence.

    Biological-event variates are keyed by event identity rather than call
    order. Angular noise is evaluated on one counter-based Brownian path, and
    event times are integrated within each step. These choices preserve the
    model equations while making resolution comparisons pathwise coupled.
    """
    if primary_type not in root_types:
        raise KeyError(f"unknown primary type {primary_type!r}")
    if duration <= 0 or dt <= 0 or max_tips <= 0:
        raise ValueError("invalid architecture integration parameters")
    nodes: list[np.ndarray] = [np.asarray(initial_position, dtype=float)]
    segments: list[ArchitectureSegment] = []
    sites: list[PotentialSite] = []
    master_seed = int(rng.integers(0, 2**32, dtype=np.uint32))
    keyed = _KeyedRandom(master_seed)
    brownian = _CoupledBrownianPath(keyed, duration, brownian_quantum)
    primary = root_types[primary_type]
    primary_spacing_rng = keyed.generator(10, 0, 0)
    tips: list[_GrowingTip] = [
        _GrowingTip(
            tip_id=0,
            node=0,
            parent_segment_id=None,
            root_type=primary_type,
            order=0,
            position=np.asarray(initial_position, dtype=float),
            angle=initial_orientation,
            age=0.0,
            arc_length=0.0,
            next_site_arc=_sample_spacing(primary, primary_spacing_rng),
            dry_memory=0.0,
            birth_time=0.0,
            mortality_time=keyed.exponential(primary.mortality_rate, 20, 0),
            dormancy_time=keyed.exponential(primary.dormancy_rate, 21, 0),
            spacing_index=1,
        )
    ]
    tip_paths: dict[int, list[int]] = {0: [0]}
    next_tip_id = 1

    def emerge_due_sites(step_end: float) -> None:
        nonlocal next_tip_id
        for site in sites:
            if (
                site.status != SiteStatus.POTENTIAL
                or site.emergence_time > step_end + 1e-12
                or len(tips) >= max_tips
            ):
                continue
            local = site.position[None, :]
            water = float(soil.sample("water", local)[0])
            nutrient = float(soil.sample("nutrient", local)[0])
            impedance = float(soil.sample("impedance", local)[0])
            parent_tip = next(
                (candidate for candidate in tips if candidate.tip_id == site.parent_tip_id),
                None,
            )
            dry_memory = 0.0 if parent_tip is None else parent_tip.dry_memory
            score = (
                response.intercept
                + response.water * water
                + response.nutrient * nutrient
                + response.impedance * impedance
                + response.carbon * carbon_factor
                + response.dry_memory * dry_memory
            )
            draw = keyed.uniform(30, site.site_id, 0)
            emergence_probability = _logistic(score)
            if draw > emergence_probability:
                site.status = (
                    SiteStatus.DORMANT
                    if keyed.uniform(30, site.site_id, 1) < response.dormancy_probability
                    else SiteStatus.ABORTED
                )
                continue
            if keyed.uniform(30, site.site_id, 2) < response.abortion_probability:
                site.status = SiteStatus.ABORTED
                continue
            successor_name = root_types[site.root_type].successor
            if successor_name is None or site.parent_order >= max_order:
                site.status = SiteStatus.DORMANT
                continue
            successor = root_types[successor_name]
            branch_angle = max(
                0.05,
                successor.branch_angle_mean
                + successor.branch_angle_sd * keyed.normal(31, site.site_id),
            )
            angle = site.parent_orientation + site.side * branch_angle
            spacing_rng = keyed.generator(10, next_tip_id, 0)
            tips.append(
                _GrowingTip(
                    tip_id=next_tip_id,
                    node=site.parent_node,
                    parent_segment_id=None,
                    root_type=successor_name,
                    order=site.parent_order + 1,
                    position=site.position.copy(),
                    angle=angle,
                    age=0.0,
                    arc_length=0.0,
                    next_site_arc=_sample_spacing(successor, spacing_rng),
                    dry_memory=dry_memory,
                    birth_time=site.emergence_time,
                    mortality_time=site.emergence_time
                    + keyed.exponential(successor.mortality_rate, 20, next_tip_id),
                    dormancy_time=site.emergence_time
                    + keyed.exponential(successor.dormancy_rate, 21, next_tip_id),
                    spacing_index=1,
                )
            )
            tip_paths[next_tip_id] = [site.parent_node]
            next_tip_id += 1
            site.status = SiteStatus.EMERGED

    time = 0.0
    while time < duration - 1e-12:
        step_end = min(time + dt, duration)
        emerge_due_sites(step_end)
        tip_index = 0
        while tip_index < len(tips):
            tip = tips[tip_index]
            tip_index += 1
            if not tip.active:
                continue
            local_start_time = max(time, tip.birth_time)
            local_end_time = min(step_end, tip.mortality_time, tip.dormancy_time)
            if local_end_time <= local_start_time + 1e-12:
                if min(tip.mortality_time, tip.dormancy_time) <= step_end + 1e-12:
                    tip.active = False
                continue
            active_dt = local_end_time - local_start_time
            root_type = root_types[tip.root_type]
            local_traits = root_type.tip_traits
            local_speed, omega, local_dr = _soil_response(
                soil,
                tip.position[None, :],
                np.asarray([tip.angle]),
                local_start_time,
                local_traits,
            )
            starting_angle = tip.angle
            angular_noise = math.sqrt(2.0 * float(local_dr[0])) * brownian.increment(
                tip.tip_id, local_start_time, local_end_time
            )
            predictor_angle = (
                starting_angle + float(omega[0]) * active_dt + angular_noise + np.pi
            ) % (2.0 * np.pi) - np.pi
            predictor_delta = (predictor_angle - starting_angle + np.pi) % (2.0 * np.pi) - np.pi
            predictor_position = tip.position + (
                float(local_speed[0])
                * carbon_factor
                * active_dt
                * np.array(
                    [
                        math.cos(starting_angle + 0.5 * predictor_delta),
                        math.sin(starting_angle + 0.5 * predictor_delta),
                    ]
                )
            )
            end_speed, end_omega, _ = _soil_response(
                soil,
                predictor_position[None, :],
                np.asarray([predictor_angle]),
                local_end_time,
                local_traits,
            )
            tip.angle = (
                starting_angle
                + 0.5 * (float(omega[0]) + float(end_omega[0])) * active_dt
                + angular_noise
                + np.pi
            ) % (2.0 * np.pi) - np.pi
            angular_change = (tip.angle - starting_angle + np.pi) % (2.0 * np.pi) - np.pi
            movement_angle = starting_angle + 0.5 * angular_change
            distance = (
                0.5 * (float(local_speed[0]) + float(end_speed[0])) * carbon_factor * active_dt
            )
            if distance <= 1e-10:
                if min(tip.mortality_time, tip.dormancy_time) <= step_end + 1e-12:
                    tip.active = False
                continue
            start = tip.position.copy()
            proposed_end = start + distance * np.array(
                [math.cos(movement_angle), math.sin(movement_angle)]
            )
            end, domain_fraction, contacted_boundary = _clip_to_domain(start, proposed_end, soil)
            distance *= domain_fraction
            active_dt *= domain_fraction
            local_end_time = local_start_time + active_dt
            if distance <= 1e-10:
                tip.active = False
                continue

            old_arc = tip.arc_length
            new_arc = old_arc + distance
            crossings: list[float] = []
            while tip.order < max_order and tip.next_site_arc <= new_arc + 1e-12:
                fraction = float(np.clip((tip.next_site_arc - old_arc) / distance, 0.0, 1.0))
                crossings.append(fraction)
                tip.next_site_arc += _sample_spacing(
                    root_type,
                    keyed.generator(10, tip.tip_id, tip.spacing_index),
                )
                tip.spacing_index += 1

            fractions = [*crossings, 1.0]
            part_start = start
            part_start_node = tip.node
            last_fraction = 0.0
            created_site = False
            for fraction in fractions:
                if fraction <= last_fraction + 1e-12:
                    continue
                part_end = start + fraction * (end - start)
                part_end_node = len(nodes)
                nodes.append(part_end.copy())
                segment_id = len(segments)
                created_time = local_start_time + fraction * active_dt
                segments.append(
                    ArchitectureSegment(
                        segment_id,
                        part_start_node,
                        part_end_node,
                        tip.parent_segment_id,
                        tip.tip_id,
                        tip.root_type,
                        tip.order,
                        tuple(part_start),
                        tuple(part_end),
                        root_type.radius,
                        created_time,
                    )
                )
                tip.parent_segment_id = segment_id
                tip_paths[tip.tip_id].append(part_end_node)
                if fraction < 1.0 - 1e-12 or any(
                    math.isclose(fraction, value, abs_tol=1e-12) for value in crossings
                ):
                    site_angle = (starting_angle + fraction * angular_change + np.pi) % (
                        2.0 * np.pi
                    ) - np.pi
                    site_id = len(sites)
                    delay = (
                        keyed.gamma(
                            2.0,
                            root_type.developmental_delay_mean / 2.0,
                            40,
                            site_id,
                        )
                        if root_type.developmental_delay_mean > 0
                        else 0.0
                    )
                    sites.append(
                        PotentialSite(
                            site_id,
                            tip.tip_id,
                            part_end_node,
                            part_end.copy(),
                            site_angle,
                            tip.order,
                            tip.root_type,
                            created_time,
                            created_time + delay,
                            -1.0 if keyed.uniform(41, site_id) < 0.5 else 1.0,
                        )
                    )
                    created_site = True
                part_start = part_end
                part_start_node = part_end_node
                last_fraction = fraction

            tip.node = part_start_node
            tip.position = end
            tip.arc_length = new_arc
            tip.age += active_dt
            water = float(soil.sample("water", end[None, :])[0])
            memory_decay = _dry_memory_decay(active_dt)
            tip.dry_memory = memory_decay * tip.dry_memory + (1.0 - memory_decay) * max(
                0.0, 0.2 - water
            )
            if contacted_boundary:
                tip.active = False
            elif min(tip.mortality_time, tip.dormancy_time) <= step_end + 1e-12:
                tip.active = False
            if created_site:
                emerge_due_sites(step_end)
        time = step_end

    return Architecture(
        np.asarray(nodes),
        tuple(segments),
        tuple(sites),
        {tip_id: tuple(path) for tip_id, path in tip_paths.items()},
        duration,
    )
