[theme]
primaryColor = "#16865c"
backgroundColor = "#fbfcfa"
secondaryBackgroundColor = "#f2f6f1"
textColor = "#172033"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
